### ISSUE TITLE
"Cannot find module 'fs/promises'"

### ISSUE THREAD

**Issue by mkarras** [CyCraft/vue-intellisense#13]
The index.cjs.js file in dist folder uses `require('fs/promises')` instead of `require('fs').promises` causing "Error: Cannot find module 'fs/promises'".

**Comment by mesqueeb** [comment]
@mkarras where does it throw that error. Can you provide reproduction steps?

**Comment by mkarras** [comment]
@mesqueeb it is thrown on console when running `vue-int --input /src/components --output vetur --recursive` or any other generating command.

Which node version do you use? For some 12.X version it won't work. Have a look [here](https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly).

**Comment by mesqueeb** [comment]
@mkarras I'm not sure how to change the way that the rollup bundles that file. I think the easiest way for me to solve this issue is to find the first nodeJS version that introduced that submodule and make that the minimum compatible nodeJS version￼￼.

**Comment by mkarras** [comment]
Tomorrow i will update to the latest node 12 version. Hopefully this fix the problem. Or I need to monkey patch your module.

**Comment by mesqueeb** [comment]
if it doesn't work let me know !

**Comment by mkarras** [comment]
Used the latest note 12 version: 12.22.1 with no success. With node 16 it worked. Need to test if nothing break with this version. Which version do you use?

Edit:
Also works with 14.16.1.

**Comment by mesqueeb** [comment]
I will try to rewrite the import logic so rollup bundles differently.

**Comment by elielr01** [comment]
I also get this error. Running the command

```shell
vue-int --input components --output vetur --recursive
```
with:

**macOS**: v11.2.3
**Node**: v10.23.1

Let me know how I can help :)

**Comment by rogier-stegeman** [comment]
Mine is also broken.
```
  internal/modules/cjs/loader.js:818
    throw err;
    ^

  Error: Cannot find module 'fs/promises'
  (...)
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '(...)/node_modules/@vue-intellisense/scripts/dist/index.cjs.js',
    '(...)/node_modules/vue-intellisense/cli.js'
  ]
```

**Comment by Sandalf** [comment]
I got the same error and also had to upgrade node to make it work.

**Failed with:** node v12.22.6

**Worked with:** node v14.17.6

**Comment by mesqueeb** [comment]
Pr welcome
